### ISSUE TITLE
Omnibar user popout bugged

### ISSUE THREAD

**Issue by sneazy-ibo** [DaBluLite/css-snippets#4]
1. Userpopout opens directly above the avatar which cuts it out, opening the user popout on the right side of the avatar would solve it
2. BetterFolders plugin moves the whole section with it after opening a folder
<img width="374" alt="image" src="https://github.com/DaBluLite/css-snippets/assets/41344259/f3a5cdcc-643c-407d-ba02-816966b20177">

**Comment by DaBluLite** [comment]
Both issues have been fixed
