### ISSUE TITLE
ConsistentChatbar x CompactUserList = chatbar extends beneath userlist

### ISSUE THREAD

**Issue by nintendraw** [DaBluLite/css-snippets#8]
Themes: Consistent Chatbar, Compact-User-List (`https://inve1951.github.io/BetterDiscordStuff`)

While ConsistentChatbar works great on servers and server forums (img1), on group DMs and forum threads (imgs 2 and 3), the chat bar appears to extend underneath my CompactUserList member list. Attempting to click on the hidden part of the emotes button doesn't work and also triggers the hover-expand action instead. This is a problem because my emotes button (my most used out of all these), and presumably any "collapse/reduce chat buttons" controls one might have, end up hidden under the user list and impossible to interact with. Can it be fixed? Thanks!

![image](https://github.com/DaBluLite/css-snippets/assets/74480507/423de9b7-fc7b-4654-be35-be05db61a356)
![image](https://github.com/DaBluLite/css-snippets/assets/74480507/3e948a2a-a3d5-44fa-b0cd-fc28e5f61c4c)
![image](https://github.com/DaBluLite/css-snippets/assets/74480507/410b819d-dc0a-4f03-979e-26d8f324a264)

**Comment by DaBluLite** [comment]
From what I can see, the compact memberlist only overflows the chatbar on hover, which is intended behavior of the snippet
